
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    enabled: false
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 192.168.52.108:8848
      discovery:
        auto-registration: true
        server-addr: 192.168.52.108:8848
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      #Redis 连接的超时时间
      timeout: 5000
      #Redis 索引（0~15，默认为0）
      database: 10
      host: 192.168.160.103
      port: 6379
      password: shengtong
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
#    url: jdbc:postgres_jts://192.168.52.224:5500/anno_database
#    username: postgres
#    password: stdev123
    url: jdbc:postgres_jts://192.168.52.183:5500/postgres
    username: postgres
    password: 123456
    driver-class-name: com.jnet.common.geo.jdbc.JtsWrapper
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 5000
      auto-commit: true
      pool-name: "HikariCP"
      connection-test-query: "SELECT 1"
      register-mbeans: true
  thymeleaf:
    check-template-location: false
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
      logic-delete-field: delFlag
  mapper-locations: classpath:mapper/*.xml
#  type-handlers-package: "com.jnet.anno.common.mybatis.jts"
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#prometheus配置
info:
  alen: alen
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.jnet.anno.controller,com.jnet.anno.vo.*
  default-flat-param-object: true
netty:
  port: 7777


