
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # nacos namespace
        namespace: f7b24ec6-54ab-43fa-85bc-6f497fc4dfec
        # nacos group
        group: DEFAULT_GROUP
        metadata:
          response-timeout: 10000
          connect-timeout: 3000
      #username: nacos
      #password: nacos
    gateway:
      routes:
        - id: image
          uri: lb://image
          predicates:
            - Path=/jnet/image/**
      default-filters:
        - StripPrefix=1
  data:
    redis:
      #Redis 连接的超时时间
      timeout: 5000
      #Redis 索引（0~15，默认为0）
      database: 0
      cluster:
        #Redis 命令执行时最多转发次数
        max-redirects: 3
        nodes: 127.0.0.1:6371,127.0.0.1:6372,127.0.0.1:6373,127.0.0.1:6374,127.0.0.1:6375,127.0.0.1:6376
      password: 1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#prometheus配置
info:
  alen: alen
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}



