spring:
  main:
    web-application-type: reactive
  application:
    name: GatewayApp
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 192.168.52.108:8848
      discovery:
        auto-registration: true
        server-addr: 192.168.52.108:8848
    gateway:
      routes:
        - id: SystemApp
          uri: lb://SystemApp
          predicates:
            - Path=/system/**
        - id: Oauth2Service
          uri: lb://Oauth2Service
          predicates:
            - Path=/oauth2Service/**
        - id: ImageService
          uri: lb://ImageService
          predicates:
            - Path=/imageService/**
      default-filters:
        - StripPrefix=1
  data:
    redis:
      #Redis 连接的超时时间
      timeout: 5000
      #Redis 索引（0~15，默认为0）
      database: 10
      host: 192.168.160.103
      port: 6379
      #      cluster:
      #        #Redis 命令执行时最多转发次数
      #        max-redirects: 3
      #        nodes: 172.31.2.70:6371,172.31.2.70:6372,172.31.2.70:6373,172.31.2.70:6374,172.31.2.70:6375,172.31.2.70:6376
      password: shengtong
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
#prometheus配置
info:
  alen: alen
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
whitelists: /oauth2Service/oauth2/token/**,/oauth2Service/oauth2/authorize/**,/oauth2Service/rsa/publicKey




